import { environment } from "environments/environment";

export const aPP_url = {
    pcfcView:environment.pcfcView,
}
export const APP_URL = {
    saveOutword: environment.saveOutword,
    countryUrl: environment.countryUrl,
    currencyUrl: environment.currencyUrl,
    accountType: environment.accountType,
    purposeCode: environment.purposeCode,
    purposeCodeDesc: environment.purposeCodeDesc,
    hsCodeDesc: environment.hsCodeDesc,
    // beneficiaryDetails: environment.beneficiaryDetails,
    commonApi: environment.commonApi,
    nostroApi: environment.nostroApi,
    lcSave: environment.lcSave,
    approveOutWard: environment.approveOutWard,
    rejectOutWard: environment.rejectOutWard,
    listView: environment.listView,
    dashboardUrl: environment.dashboardUrl,
    outwardEdit: environment.outwardEdit,
    outwardView: environment.outwardView,
    pieChartUrl:environment.pieChartUrl,
    BarChartApi:environment.BarChartApi,
    dashBarPieList:environment.dashBarPieList,
    draftUrl:environment.draftUrl,
    updateDraft:environment.updateDraft,
    lcUpdate:environment.lcUpdate,
    lcApproveOutWard:environment.lcApproveOutWard,
    lcRejectOutWard:environment.lcRejectOutWard,
    saveUpload:environment.saveUpload,
    documentView:environment.documentView,
    updateOutword: environment.updateOutword,
    lcListView:environment.lcListView,
    incoterms:environment.incoterms,
    getDocType:environment.getDocType,
    getDocDescList:environment.getDocDescList,
    getDocCodeList:environment.getDocCodeList,
    hscCode:environment.hscCode,
    lcView:environment.lcView,
    LcEdit:environment.LcEdit,
    LcUpdateDraft:environment.LcUpdateDraft,
    LcDraft:environment.LcDraft,
    advSaveDraft:environment.advSaveDraft,
    advDraftUpdate:environment.advDraftUpdate,
    advRemUpdate:environment.advRemUpdate,
    advSaveForm:environment.advSaveForm,
    advListView:environment.advListView,
    advView:environment.advView,
    advEdit:environment.advEdit,
    advApproveForm:environment.advApproveForm,
    advRejectForm:environment.advRejectForm,
    pcfcSave:environment.pcfcSave,
    pcfcView:environment.pcfcView,
    pcfcEdit:environment.pcfcEdit,
    pcfcApprove:environment.pcfcApprove,
    pcfcReject:environment.pcfcReject,
    pcfcListView:environment.pcfcListView,
    pcfcUpdate:environment.pcfcUpdate,
    pcfcDraft:environment.pcfcDraft,
    pcfcDraftUpdate:environment.pcfcDraftUpdate,
    billSave:environment.billSave,
    billListView:environment.billListView,
    billView:environment.billView,
    billEdit:environment.billEdit,
    billUpdate:environment.billUpdate,
    billDraft:environment.billDraft,
    updateBillDraft:environment.updateBillDraft,
    billApproveForm:environment.billApproveForm,
    billRejectForm:environment.billRejectForm,
    cpfcSaveForm:environment.cpfcSaveForm,
    CpfcUpdate:environment.CpfcUpdate,
    CpfcDraft:environment.CpfcDraft,
    // updateCpfcDraft:environment.updateCpfcDraft,
    CpfcApproveForm:environment.CpfcApproveForm,
    CpfcRejectForm:environment.CpfcRejectForm,
    cpfcView:environment.cpfcView,
    cpfcEdit:environment.cpfcEdit,
    updateCpfcDraft:environment.updateCpfcDraft,
    cpfcListView:environment.cpfcListView,
    importBillCollectionSave:environment.importBillCollectionSave,
    importBillCollectionUpdate:environment.importBillCollectionUpdate,
    importBillCollectionApprove:environment.importBillCollectionApprove,
    importBillCollectionReject:environment.importBillCollectionReject,
    importBillCollectionListAPi:environment.importBillCollectionListAPi,
    importBillCollectionView:environment.importBillCollectionView,
    importBillCollectionEdit:environment.importBillCollectionEdit,
    updateImportBillDraft:environment.updateImportBillDraft,
    ImportBillDraft:environment.ImportBillDraft,
    fwrdCntSave:environment.fwrdCntSave,
    fwrdCntUpdate:environment.fwrdCntUpdate,
    fwrdCntList:environment.fwrdCntList,
    fwrdCntView:environment.fwrdCntView,
    fwrdCntEdit:environment.fwrdCntEdit,
    fwrdCntApprove: environment.fwrdCntApprove,
    fwrdCntReject: environment.fwrdCntReject,
    fwrdCntDraft:environment.fwrdCntDraft,
    fwrdCntDraftUpdate:environment.fwrdCntDraftUpdate,
    processType:environment.processType,
    gaurntyListView:environment.gaurntyListView,
    gurntySave:environment.gurntySave,
    gurntyUpdate:environment.gurntyUpdate,
    gurntyView:environment.gurntyView,
    gurntyEdit:environment.gurntyEdit,
    gurntyApprove:environment.gurntyApprove,
    gurntyReject:environment.gurntyReject,
    gurntyDraft:environment.gurntyDraft,
    gurntyUpdateDraft:environment.gurntyUpdateDraft,
    lcAmenedmnetSave:environment.lcAmenedmnetSave,

 }

 

