export const environment = {
    production: true,
    // app_url:'http://localhost:333/CNDMSNETBNK/changes/datas',
    // aPP_url: 'http://localhost:8087/CNDMSNETWEB/changes/datas',
    // app_url: 'http://43.240.64.161:7001/CNDMSNETWEB/changes/datas',
    // app_url: 'http://43.240.64.161:7001/CNDMSNETWEB/changes/datas',
    //app_url: 'https://59.144.189.105/CNDMSNETWEB/changes/datas',
    // app_url: 'https://testunnat.canarabank.in/CNDMSNETWEB/changes/datas',
     app_url: 'https://canfxib.canarabank.com/CNDMSNETWEB/changes/datas',
   // app_url: 'https://10.33.192.5/CNDMSNETWEB/changes/datas',
    countryUrl: 'location/country',
    currencyUrl: 'CuurencyMaster/currency',
    accountType: 'BankMaster/branch',
    purposeCode: 'purposeMaster/purposecode',
    purposeCodeDesc: 'purposeMaster/purposeDesc/',
    hsCodeDesc: 'ajaxLoad/chkHsCode/',
    commonApi: 'commonmaster/masterbytype/',
    nostroApi: 'NostroMaster/NostroCode',
    saveOutword: 'outwrdRmtnceLoad/save',
    updateOutword: 'outwrdRmtnceLoad/update',
    lcSave: 'lcFormLoad/save',
    lcUpdate: 'lcFormLoad/update',
    approveOutWard: 'outwrdRmtnceLoad/approved',
    rejectOutWard: 'outwrdRmtnceLoad/outwrdRmtnceReject',
    listView: 'outwrdRmtnceLoad/search',
    pieChartUrl: 'dashBoard/dashBoardPieChartLoad',
    dashboardUrl: 'login/user/userId/days-All',
    outwardView: 'outwrdRmtnceLoad/view/',
    outwardEdit: 'outwrdRmtnceLoad/edit/',
    BarChartApi: 'dashBoard/dashBoardLoad',
    dashBarPieList: 'dashBoard/dashBoardProcessList',
    draftUrl: 'outwrdRmtnceLoad/draft',
    updateDraft: 'outwrdRmtnceLoad/updateDraft',
    lcApproveOutWard: 'lcFormLoad/approved',
    lcRejectOutWard: 'lcFormLoad/lcFormReject',
    saveUpload: 'lcFormLoad/upload',
    documentView: 'lcFormLoad/doc/bpm/docPath/docNm',
    lcListView: 'lcFormLoad/search',
    incoterms: 'INCOTERMS',
    getDocType: 'ajaxLoad/getDocMstTpList',
    getDocDescList: 'ajaxLoad/getDocDescList',
    getDocCodeList: 'ajaxLoad/getDocCodeList',
    hscCode: 'ajaxLoad/chkHsCode',
    lcView: 'lcFormLoad/view/',
    LcEdit: 'lcFormLoad/edit/',
    LcUpdateDraft: 'lcFormLoad/draftUpdate',
    LcDraft: 'lcFormLoad/draft',
    advDraft: 'advRemFormLoad/draft',
    advDraftUpdate: 'advRemFormLoad/draftUpdate',
    advSaveForm: 'advRemFormLoad/save',
    advRemUpdate: 'advRemFormLoad/update',
    advSaveDraft: 'advRemFormLoad/draft',
    advListView: 'advRemFormLoad/search',
    advView: 'advRemFormLoad/view/',
    advEdit: 'advRemFormLoad/edit/',
    advApproveForm: 'advRemFormLoad/approved',
    advRejectForm: 'advRemFormLoad/advRemFormReject',
    pcfcSave: 'pcfcFormLoad/save',
    pcfcView: 'pcfcFormLoad/view/',
    pcfcEdit: 'pcfcFormLoad/edit/',
    pcfcApprove: 'pcfcFormLoad/approved',
    pcfcReject: 'pcfcFormLoad/pcfcFormReject',
    pcfcListView: 'pcfcFormLoad/search',
    pcfcUpdate: 'pcfcFormLoad/update',
    pcfcDraft: 'pcfcFormLoad/draft',
    pcfcDraftUpdate: 'pcfcFormLoad/draftUpdate',
    billSave: 'expBillsFormLoad/save',
    billListView: 'expBillsFormLoad/search',
    billView: 'expBillsFormLoad/view',
    billEdit: 'expBillsFormLoad/edit',
    billUpdate: 'expBillsFormLoad/update',
    billDraft: 'expBillsFormLoad/draft',
    updateBillDraft: 'expBillsFormLoad/updateDraft',
    billRejectForm: 'expBillsFormLoad/exportBillsReject',
    billApproveForm: 'expBillsFormLoad/approved',
    cpfcSaveForm: 'inwrdRmtnceLoad/save',
    CpfcUpdate: 'inwrdRmtnceLoad/update',
    CpfcDraft: 'inwrdRmtnceLoad/draft',
    CpfcApproveForm: 'inwrdRmtnceLoad/approved',
    CpfcRejectForm: 'inwrdRmtnceLoad/inwrdRmtnceReject',
    CpcfcEditForm: 'inwrdRmtnceLoad/edit',
    CpcfcViewApi: 'inwrdRmtnceLoad/view',
    cpfcEdit: 'inwrdRmtnceLoad/edit',
    cpfcView: 'inwrdRmtnceLoad/view',
    updateCpfcDraft: 'inwrdRmtnceLoad/updateDraft',
    cpfcListView: 'inwrdRmtnceLoad/search',
    importBillCollectionSave: 'importBillsLoad/save',
    importBillCollectionUpdate: 'importBillsLoad/update',
    importBillCollectionListAPi: 'importBillsLoad/search',
    importBillCollectionView: 'importBillsLoad/view',
    importBillCollectionEdit: 'importBillsLoad/edit',
    importBillCollectionReject: 'importBillsLoad/importBillsReject',
    importBillCollectionApprove: 'importBillsLoad/approved',
    updateImportBillDraft: 'importBillsLoad/updateDraft',
    ImportBillDraft: 'importBillsLoad/draft',
    fwrdCntSave: 'fwdCntFormLoad/save',
    fwrdCntUpdate: 'fwdCntFormLoad/update',
    fwrdCntList: 'fwdCntFormLoad/search',
    fwrdCntView: 'fwdCntFormLoad/view',
    fwrdCntEdit: 'fwdCntFormLoad/edit',
    fwrdCntReject: 'fwdCntFormLoad/fwdCntFormReject',
    fwrdCntApprove: 'fwdCntFormLoad/approved',
    fwrdCntDraft: 'fwdCntFormLoad/draft',
    fwrdCntDraftUpdate: 'fwdCntFormLoad/draftUpdate',
    processType: 'processType/process',
    gaurntyListView: 'guaranteeFormLoad/search',
    gurntySave: 'guaranteeFormLoad/save',
    gurntyUpdate: 'guaranteeFormLoad/update',
    gurntyView: 'guaranteeFormLoad/view',
    gurntyEdit: 'guaranteeFormLoad/edit',
    gurntyApprove: 'guaranteeFormLoad/approved',
    gurntyReject: 'guaranteeFormLoad/GuaranteeFormReject',
    gurntyDraft: 'guaranteeFormLoad/draft',
    gurntyUpdateDraft: 'guaranteeFormLoad/draftUpdate',
    lcAmenedmnetSave: 'lcAmendFormLoad/save',
    encryptKey: 'YJm1xrdQ/y69erqzFJY2x+KkcTiborC9GcIN2woBIG0=',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
